export let  arrOfApplication = 
  [
    {
      id:1,
      AppName:"Akhanda",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:3,
      CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:112,
      AppName:"asdfasf",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:3,
      CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:2,
      AppName:"Bahubali",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:3,
      AppName:"RRR",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:4,
      AppName:"Pushpa",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:3,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:5,
        AppName:"Brahmastra",
        imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
        rating:2,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:6,
      AppName:"PSPK OG",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:7,
      AppName:"Tholi Prema",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:8,
      AppName:"Thammudu",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[
        {
            id:"1",
            imageUrl:"https://www.shutterstock.com/image-vector/single-icon-database-isolated-on-260nw-1725039880.jpg",
            movie:"akhanda"
        }
      ]
    },
    {
      id:9,
      AppName:"Shutter Island",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:10,
      AppName:"Interstellar",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:11,
      AppName:"Liger",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:12,
      AppName:"Radhe Shyam",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:13,
      AppName:"World famous lover",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:14,
      AppName:"Joker",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:15,
      AppName:"The Dark knight",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:16,
      AppName:"Fight Club",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:5,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:17,
      AppName:"Avengers Infinity War",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:18,
      AppName:"KGF",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:4,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:19,
      AppName:"Zero",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
    {
      id:20,
      AppName:"Thugs of Hindustan",
      imageUrl:"https://img.freepik.com/free-vector/illustration-data-folder-icon_53876-6329.jpg?w=2000",
      rating:1,CreatedBy:"",
      AppDescription:"",
      environment:[]
    },
  ];